version: '3.4'

services:
  songbookservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTP_PORT=8088
      - ASPNETCORE_HTTPS_PORT=8089
    ports:
        - "8088:80/tcp"
        - "8089:443/tcp"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro